services:
  emsi-ebank-discovery-service:  #1er service et tous ce dessus sont votre configuration
    build: ./discovery-service
    container_name: emsi-ebank-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      retries: 4
  emsi-ebank-config-service:
    build: ./config-service
    container_name: emsi-ebank-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://emsi-ebank-discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      emsi-ebank-discovery-service:
        condition: service_healthy #pour attender le demmarage de service discovery avec condition : c'est attender le reponse de healthy . si success donc config-service va demarrer , sinon il ne peut  demarre pas
  emsi-ebank-customer-service:
    build: ./customer-service
    container_name: emsi-ebank-customer-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - DISCOVERY_SERVICE_URL=http://emsi-ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://emsi-ebank-config-service:9999
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8081/actuator/health"]
      interval: 10s
      retries: 5
    depends_on:
      emsi-ebank-config-service:
        condition: service_healthy
  emsi-ebank-account-service:
    build: ./account-service
    container_name: emsi-ebank-account-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://emsi-ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://emsi-ebank-config-service:9999
    depends_on:
      emsi-ebank-customer-service:
        condition: service_healthy
  emsi-ebank-gateway-service:
    build: ./gateway-service
    container_name: container-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://emsi-ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://emsi-ebank-config-service:9999
    depends_on:
      emsi-ebank-config-service:
        condition: service_healthy

  front-end-angular:
    build: ./angular-front-end
    container_name: Conteneur-front-end
    ports:
      - '80:80'
    expose:
      - '80'





